import { useEffect, useMemo, useState } from 'react'
import { DeleteOutlined, FileTextOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons'
import { Button, Empty, Input, Modal, Popconfirm, Select, Tag, message } from 'antd'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'

type Job={id:string;company?:string;title:string;location?:string;created_at:string;match_count:number;requirements?:{industries?:string[]};conversation_id?:string}
export default function JobsPage(){const navigate=useNavigate();const[jobs,setJobs]=useState<Job[]>([]);const[q,setQ]=useState('');const[industry,setIndustry]=useState('');const[open,setOpen]=useState(false);const[title,setTitle]=useState('');const[company,setCompany]=useState('');const[location,setLocation]=useState('');
 const load=()=>api<{items:Job[]}>('/api/jobs').then(x=>setJobs(x.items));useEffect(()=>{void load()},[]);const industries=useMemo(()=>Array.from(new Set(jobs.flatMap(j=>j.requirements?.industries||[]))),[jobs]);const filtered=jobs.filter(j=>`${j.company||''}${j.title}${j.location||''}`.toLowerCase().includes(q.toLowerCase())&&(!industry||j.requirements?.industries?.includes(industry)));const create=async()=>{if(!title.trim()){message.warning('请填写岗位名称');return}try{await api('/api/jobs',{method:'POST',body:JSON.stringify({company,title,raw_text:'',requirements:{company,title,industries:industry?[industry]:[],locations:location?[location]:[],minimum_years:0,skills:[],management_required:false,must_have:[],preferred:[],performance_expectations:[]}})});message.success('岗位已创建');setOpen(false);setTitle('');setCompany('');setLocation('');load()}catch(e){message.error(e instanceof Error?e.message:'创建失败')}};const remove=async(id:string)=>{try{await api(`/api/jobs/${id}`,{method:'DELETE'});message.success('岗位及其会话已删除');load()}catch(e){message.error(e instanceof Error?e.message:'删除失败')}};const openJob=async(job:Job)=>{if(job.conversation_id){navigate('/',{state:{conversationId:job.conversation_id}});return}try{const x=await api<{conversation_id:string}>(`/api/jobs/${job.id}/conversation`);navigate('/',{state:{conversationId:x.conversation_id}})}catch{navigate('/')}};
 return <div className="page"><header className="page-head"><div><p className="eyebrow">JOB WORKSPACE</p><h1>岗位</h1><p>按公司、岗位和地点查找历史招聘项目。</p></div><div className="job-actions"><Button onClick={()=>navigate('/')}>让 AI 创建岗位</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>手动新增岗位</Button></div></header><section className="panel job-toolbar"><Input prefix={<SearchOutlined/>} allowClear placeholder="搜索公司、岗位或地点" value={q} onChange={e=>setQ(e.target.value)}/><Select allowClear placeholder="行业" value={industry||undefined} onChange={v=>setIndustry(v||'')} options={industries.map(x=>({value:x,label:x}))}/></section><section className="panel jobs-table"><div className="jobs-head"><span>公司 / 岗位</span><span>地点</span><span>行业</span><span>候选人</span><span>更新时间</span><span></span></div>{filtered.map(job=><div className="jobs-row" key={job.id} onClick={()=>openJob(job)}><span><b>{job.company||'未指定公司'}</b><strong>{job.title}</strong></span><span>{job.location||'未指定'}</span><span>{job.requirements?.industries?.join('、')||'行业未指定'}</span><span>{job.match_count} 人</span><span>{new Date(job.created_at).toLocaleDateString('zh-CN')}</span><span onClick={e=>e.stopPropagation()}><Popconfirm title="删除岗位及其问答记录？" onConfirm={()=>remove(job.id)}><Button type="text" danger icon={<DeleteOutlined/>}/></Popconfirm></span></div>)}{!filtered.length&&<Empty description={jobs.length?'没有匹配岗位':'还没有岗位，先让 AI 创建一个岗位吧'}/>}</section><Modal open={open} title="手动新增岗位" okText="创建岗位" cancelText="取消" onOk={create} onCancel={()=>setOpen(false)}><Input placeholder="公司名称（可选）" value={company} onChange={e=>setCompany(e.target.value)} style={{marginBottom:12}}/><Input placeholder="岗位名称" value={title} onChange={e=>setTitle(e.target.value)} style={{marginBottom:12}}/><Input placeholder="工作地点（可选）" value={location} onChange={e=>setLocation(e.target.value)}/></Modal></div>}
